-- MySQL Script generated by MySQL Workbench
-- Sun Oct 10 20:59:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autor` (
  `idAutor` INT NOT NULL AUTO_INCREMENT,
  `NombreAutor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAutor`),
  UNIQUE INDEX `numero_inventario_UNIQUE` (`NombreAutor` ASC) VISIBLE,
  UNIQUE INDEX `idLibro_UNIQUE` (`idAutor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ISBN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ISBN` (
  `idISBN` INT NOT NULL AUTO_INCREMENT,
  `ISBN` INT NOT NULL,
  PRIMARY KEY (`idISBN`, `ISBN`),
  UNIQUE INDEX `numero_inventario_UNIQUE` (`ISBN` ASC) VISIBLE,
  UNIQUE INDEX `idLibro_UNIQUE` (`idISBN` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `categorianombre` VARCHAR(30) NOT NULL,
  `DescripcionCategoria` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`),
  UNIQUE INDEX `numero_inventario_UNIQUE` (`categorianombre` ASC) VISIBLE,
  UNIQUE INDEX `idLibro_UNIQUE` (`idCategoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Editorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Editorial` (
  `idEditorial` INT NOT NULL AUTO_INCREMENT,
  `NombreEditorial` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEditorial`),
  UNIQUE INDEX `numero_inventario_UNIQUE` (`NombreEditorial` ASC) VISIBLE,
  UNIQUE INDEX `idLibro_UNIQUE` (`idEditorial` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Libros` (
  `idLibro` INT NOT NULL AUTO_INCREMENT,
  `numero_inventario` VARCHAR(45) NOT NULL,
  `stock` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `nombre` VARCHAR(256) NULL,
  `Autor_idAutor` INT NOT NULL,
  `ISBN_idISBN` INT NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  `idEditorial` INT NOT NULL,
  PRIMARY KEY (`idLibro`, `Autor_idAutor`, `Categoria_idCategoria`),
  UNIQUE INDEX `numero_inventario_UNIQUE` (`numero_inventario` ASC) VISIBLE,
  UNIQUE INDEX `idLibro_UNIQUE` (`idLibro` ASC) VISIBLE,
  INDEX `fk_Libros_Autor1_idx` (`Autor_idAutor` ASC) VISIBLE,
  INDEX `fk_Libros_ISBN1_idx` (`ISBN_idISBN` ASC) VISIBLE,
  INDEX `fk_Libros_Categoria1_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  INDEX `fk_Libros_Editorial_idx` (`idEditorial` ASC) VISIBLE,
  CONSTRAINT `fk_Libros_Autor1`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `mydb`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libros_ISBN1`
    FOREIGN KEY (`ISBN_idISBN`)
    REFERENCES `mydb`.`ISBN` (`idISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libros_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libros_Editorial`
    FOREIGN KEY (`idEditorial`)
    REFERENCES `mydb`.`Editorial` (`idEditorial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TiposUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TiposUsuario` (
  `idTipoUsuario` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_apellido` VARCHAR(80) NOT NULL,
  `dni` VARCHAR(15) NOT NULL,
  `idTipoUsuario` INT NOT NULL,
  `CorreoUsuario` VARCHAR(45) NOT NULL,
  `UsuariosDireccion` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idEstudiantes_UNIQUE` (`idUsuario` ASC) VISIBLE,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  INDEX `Usuario_TIpoUsuario_idx` (`idTipoUsuario` ASC) VISIBLE,
  CONSTRAINT `Usuario_TIpoUsuario`
    FOREIGN KEY (`idTipoUsuario`)
    REFERENCES `mydb`.`TiposUsuario` (`idTipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TiempoEstadia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TiempoEstadia` (
  `idTiempoEstadia` INT NOT NULL AUTO_INCREMENT,
  `TiempoEstadia` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idTiempoEstadia`),
  UNIQUE INDEX `numero_inventario_UNIQUE` (`TiempoEstadia` ASC) VISIBLE,
  UNIQUE INDEX `idLibro_UNIQUE` (`idTiempoEstadia` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Movimientos` (
  `idMovimientos` INT NOT NULL AUTO_INCREMENT,
  `idEstudiante` INT NOT NULL,
  `IdLibro` INT NOT NULL,
  `cantidad` INT(3) NOT NULL DEFAULT 0,
  `esRetiro` TINYINT NOT NULL DEFAULT 0,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `TiempoEstadia_idTiempoEstadia` INT NOT NULL,
  PRIMARY KEY (`idMovimientos`, `TiempoEstadia_idTiempoEstadia`),
  UNIQUE INDEX `idMovimientos_UNIQUE` (`idMovimientos` ASC) VISIBLE,
  INDEX `Libros_Movimientos_idx` (`IdLibro` ASC) VISIBLE,
  INDEX `Estudiantes_Movimientos_idx` (`idEstudiante` ASC) VISIBLE,
  INDEX `fk_Movimientos_TiempoEstadia1_idx` (`TiempoEstadia_idTiempoEstadia` ASC) VISIBLE,
  CONSTRAINT `Libros_Movimientos`
    FOREIGN KEY (`IdLibro`)
    REFERENCES `mydb`.`Libros` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Estudiantes_Movimientos`
    FOREIGN KEY (`idEstudiante`)
    REFERENCES `mydb`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movimientos_TiempoEstadia1`
    FOREIGN KEY (`TiempoEstadia_idTiempoEstadia`)
    REFERENCES `mydb`.`TiempoEstadia` (`idTiempoEstadia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carrera` (
  `idCarrera` INT NOT NULL AUTO_INCREMENT,
  `NombreCarrera` VARCHAR(45) NOT NULL,
  `AñoCarrera` INT NULL,
  PRIMARY KEY (`idCarrera`),
  UNIQUE INDEX `numero_inventario_UNIQUE` (`NombreCarrera` ASC) VISIBLE,
  UNIQUE INDEX `idLibro_UNIQUE` (`idCarrera` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carrera_has_Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carrera_has_Usuarios` (
  `Carrera_idCarrera` INT NOT NULL,
  `Usuarios_idUsuario` INT NOT NULL,
  PRIMARY KEY (`Carrera_idCarrera`, `Usuarios_idUsuario`),
  INDEX `fk_Carrera_has_Usuarios_Usuarios1_idx` (`Usuarios_idUsuario` ASC) VISIBLE,
  INDEX `fk_Carrera_has_Usuarios_Carrera1_idx` (`Carrera_idCarrera` ASC) VISIBLE,
  CONSTRAINT `fk_Carrera_has_Usuarios_Carrera1`
    FOREIGN KEY (`Carrera_idCarrera`)
    REFERENCES `mydb`.`Carrera` (`idCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carrera_has_Usuarios_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuario`)
    REFERENCES `mydb`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
